<?php

/**
 * @file
 * Enhanced control over the CSS Classes of any Block.
 *
 * Block Class allows users to add classes to any block through the block's
 * configuration interface. This implementation is based on an alteration of
 * the Core block database table to leverage the Core Block API functions,
 * objects and structure.
 */

/**
 * Implements hook_permission().
 */
function custom_permission() {
  return array(
    'administer custom module' => array(
      'title' => t('Administer custom module'),
      'description' => t('Custom script loaded in.'),
    ),
  );
}

// drupal_add_js(drupal_get_path('module', 'custom') . '/js/loader.js', 'file');
// drupal_add_js(drupal_get_path('module', 'custom') . '/js/header.js', 'file');

// Load homepage slider JS
function custom_node_view($node, $view_mode, $langcode) {
  // if($node->type == 'homepage') {
  
  //}
    $node->content['#attached']['js'][] = array
    (
      'type' => 'file',
      'data' => drupal_get_path('module', 'custom') . '/js/global/header.js',
      'group' => JS_THEME,
      'preprocess' => TRUE,
      'scope' => 'footer',
      'weight' => '999',
    );
    // $node->content['#attached']['js'][] = array
    // (
    //   'type' => 'file',
    //   'data' => drupal_get_path('module', 'custom') . '/js/global/loader.js',
    //   'group' => JS_THEME,
    //   'preprocess' => TRUE,
    //   'scope' => 'footer',
    //   'weight' => '999',
    // );
    $node->content['#attached']['js'][] = array
    (
      'type' => 'file',
      'data' => drupal_get_path('module', 'custom') . '/js/global/line.js',
      'group' => JS_THEME,
      'preprocess' => TRUE,
      'scope' => 'footer',
      'weight' => '999',
    );

  if($node->type == 'case_study') {
    $node->content['#attached']['js'][] = array
    (
      'type' => 'file',
      'data' => drupal_get_path('module', 'custom') . '/js/global/tiltslider.js',
      'group' => JS_THEME,
      'preprocess' => TRUE,
      'scope' => 'footer',
      'weight' => '999',
    );
    $node->content['#attached']['js'][] = array
    (
      'type' => 'file',
      'data' => drupal_get_path('module', 'custom') . '/js/global/classie.js',
      'group' => JS_THEME,
      'preprocess' => TRUE,
      'scope' => 'footer',
      'weight' => '998',
    );
    $node->content['#attached']['js'][] = array
    (
      'type' => 'file',
      'data' => drupal_get_path('module', 'custom') . '/js/global/prototype.js',
      'group' => JS_THEME,
      'preprocess' => TRUE,
      'scope' => 'footer',
      'weight' => '997',
    );
  }
  //drupal_add_js(drupal_get_path('module', 'custom') . 'js/global/header.js');
  //drupal_add_js(drupal_get_path('module', 'custom') . 'js/global/loader.js');

 // drupal_add_js(drupal_get_path('module', 'custom').'js/global/header.js', 'module');
}

// Load JS
// function loader_node_view($node, $view_mode, $langcode) {
//   $node->content['#attached']['js'][] = array
//   (
//     'type' => 'file',
//     'data' => path_to_theme() . '/js/global/loader.js',
//     'group' => JS_THEME,
//     'preprocess' => TRUE,
//     'scope' => 'footer',
//     'weight' => '999',
//   );
// }